name: CI

on:
  [push]
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 360000 #(100 hours)

    steps:

      # this needs the latest git!! (version 2.28)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: SPEC CPU Benchmark
        run: bash retrowrite_ci/runner.sh
